from __future__ import annotations

import json
from pathlib import Path


def _top_risks(summary: dict) -> list[str]:
    risks = (summary.get("risks") or {})

    out: list[str] = []

    god_files = risks.get("god_files") or []
    for fp in god_files[:3]:
        out.append(f"- **[god file]** `{fp}`")

    large_files = risks.get("large_files") or []
    for fp in large_files[:3]:
        out.append(f"- **[large file]** `{fp}`")

    if risks.get("missing_tests"):
        out.append("- **[missing tests]** No obvious tests directory/config detected")

    if risks.get("circular_imports"):
        out.append("- **[circular imports]** Possible circular import(s) detected (see artifacts)")

    return out[:3]


def render_pr_comment(summary_json_path: str, workflow_run_url: str | None) -> str:
    summary_path = Path(summary_json_path)
    summary = json.loads(summary_path.read_text(encoding="utf-8"))

    repo_name = summary.get("repo_name") or "(unknown)"

    lines: list[str] = []
    lines.append("RepoScope report")
    lines.append("")
    lines.append(f"Repo: `{repo_name}`")
    lines.append("")

    lines.append("Top risks detected:")
    top = _top_risks(summary)
    if not top:
        lines.append("- **[none detected]**")
    else:
        lines.extend(top)
    lines.append("")

    if workflow_run_url:
        lines.append(f"Artifacts: {workflow_run_url}")
        lines.append("")

    lines.append("Generated by RepoScope (deterministic analysis + optional AI explanations).")

    return "\n".join(lines)
